// TEMPORARY FILE - Replace this when you create the yajid-staging Firebase project
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_staging.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-cLcJqPnfeJvjOOH0IbFiK4nECvEI3u4',
    appId: '1:120731919247:android:771b0c5098df3ce16ba1fa',
    messagingSenderId: '120731919247',
    projectId: 'yajid-connect',
    storageBucket: 'yajid-connect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiYBEsg205u_hrQrohJWxlOiNFQoHXFOI',
    appId: '1:120731919247:ios:fdb4e78d8e39d29c6ba1fa',
    messagingSenderId: '120731919247',
    projectId: 'yajid-connect',
    storageBucket: 'yajid-connect.firebasestorage.app',
    iosBundleId: 'ndjinns.yajid.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-cLcJqPnfeJvjOOH0IbFiK4nECvEI3u4',
    appId: '1:120731919247:web:771b0c5098df3ce16ba1fa',
    messagingSenderId: '120731919247',
    projectId: 'yajid-connect',
    authDomain: 'yajid-connect.firebaseapp.com',
    storageBucket: 'yajid-connect.firebasestorage.app',
  );
}
